---

- hosts: all
  become: true
  remote_user: user
  tasks:

############## Debian system config ###############


# Installing apache services on CentOS and Debian systems
  - name: install apache and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
   #when: ansible_distribution in ["Debian", "Ubuntu"]


############### CentOS system config ################

    
# Installing apache2 services on all CentOS systems
  - name: install apache2 package
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

