---
# install updates on all servers
- hosts: all
  become: true
  remote_user: user
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  remote_user: user
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

# Installing apache2 services on web-servers

- hosts: web_servers
  become: true
  remote_user: user
  tasks:

  - name: install apache and php packages
    tags: apache,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    tags: apache,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: start httpd services (CentOS)
    tags: centos,apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

# copy default site files to web servers

  - name: copy default html file for site
    tags: ubuntu,centos
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

# Installing mariadb services on db-servers

- hosts: db_servers
  become: true
  remote_user: user
  tasks:

  - name: install mariadb packages (Ubuntu)
    tags: mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install mariadb package (CentOS)
    tags: mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

# install samba on all file-servers

- hosts: file_servers
  become: true
  remote_user: user
  tasks:

  - name: install samba packages on all file_servers
    tags: samba
    package:
      name: samba
      state: latest

