---
# install updates on all servers
- hosts: all
  become: true
#  remote_user: user
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

# creating new user on host machines

- hosts: all
  become: true
#  remote_user: user
  tasks:

  - name: add ssh key for z103 to hosts
    tags: always
    authorized_key:
      user: z103
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICiXOdaIm6isvAFdlGEVDBCaxeF9i4FsWUMUS5QKyTDw user@ansible-controller"

# install terraform on workstation
- hosts: workstations
  become: true
#  remote_user: user
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

# Installing apache2 services on web-servers
- hosts: web_servers
  become: true
#  remote_user: user
  tasks:

       # install apache2 on ubuntu
  - name: install apache and php packages
    tags: apache,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
       # install apache2 on linux
  - name: install apache2 package
    tags: apache,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

       # start https services
  - name: start httpd services (CentOS)
    tags: centos,apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

       # change a line in a file or doc
  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin smooth@torengit.lab
    when: ansible_distribution == "CentOS"
    register: httpd

       # restart httpd service on CentOS
  - name: restart httpd services (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

       # copy default site files to web servers
  - name: copy default html file for site
    tags: ubuntu,centos
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

# Installing mariadb services on db-servers
- hosts: db_servers
  become: true
#  remote_user: user
  tasks:

       # install mariadb on unbuntu
  - name: install mariadb packages (Ubuntu)
    tags: mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

        # install mariadb on CentOS
  - name: install mariadb package (CentOS)
    tags: mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

# install samba on all file-servers
- hosts: file_servers
  become: true
#  remote_user: user
  tasks:

  - name: install samba packages on all file_servers
    tags: samba
    package:
      name: samba
      state: latest

