       # install httpd on centos
- name: install httpd package (CentOS)
   tags: apache,centos,httpd
   dnf:
     name:
       - httpd
       - php
     state: latest
  when: ansible_distribution == "CentOS"
 
- name: start and enable httpd (CentOS)
   tags: apache,centos,httpd
   service:
     name: httpd
     state: started
     enabled: yes
  when: ansible_distribution == "CentOS"

       # install apache2 on ubuntu
- name: install apache and php packages
   tags: apache,ubuntu
   apt:
     name:
       - apache2
       - libapache2-mod-php
     state: latest
     update_cache: yes
  when: ansible_distribution == "Ubuntu"

       # change a line in a file or doc
- name: change e-mail address for admin
   tags: apache,centos,httpd
   lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^ServerAdmin'
     line: ServerAdmin smooth@torengit.lab
  when: ansible_distribution == "CentOS"
  register: httpd

       # restart httpd service on CentOS
- name: restart httpd services (CentOS)
   tags: apache,centos,httpd
   service:
     name: httpd
     state: restarted
  when: httpd.changed

       # copy default site files to web servers
- name: copy default html file for site
   tags: ubuntu,centos
   copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644

